### ISSUE TITLE
Bold variants for .psfu fonts

### ISSUE THREAD

**Issue by chromer030** [fcambus/spleen#30]
Thanks very much for this wonderful font, please add a bold variant for .psfu fonts , for linux console , it will looks brillant.

**Comment by fcambus** [comment]
I'm generally not a fan of bold characters for monospaced fonts, and it is not possible to have bold characters for the 5x8, 6x12 and 8x16 variants because most characters would overlap with each other.

Morever, there was no bold support in text mode on IBM PC, and framebuffer consoles on Linux, OpenBSD, and NetBSD do not support bold characters either.

Color highlighting should be preferred instead.
